propel:
    paths:
        outputDir: ./target/
    database:
        connections:
            myito:
                adapter: pgsql
                classname: Propel\Runtime\Connection\ConnectionWrapper
                dsn: pgsql:host=localhost;port=5432;dbname=myito;user=postgres;password=12345    
                user: postgres
                password: 12345
                settings: 
                    charset: utf8
                    queries:
                        utf8: "SET NAMES 'UTF8'"
    runtime:
        defaultConnection: myito
        connections:
        - myito
    generator:
        defaultConnection: myito
        connections:
        - myito
